// packages/visual-builder/examples/react/ArgwsPage.jsx
import {useEffect,useRef} from 'react';
import '@argws/visual-builder';
import '@argws/visual-builder/styles.css';
export default function ArgwsPage({documentUrl='/api/pages/home'}) {
  const ref=useRef(null);
  useEffect(()=>{fetch(documentUrl).then(r=>r.json()).then(p=>{ref.current.document=p.data?.document??p.document??p;});},[documentUrl]);
  return <argws-page-renderer ref={ref}></argws-page-renderer>;
}

// packages/visual-builder/examples/svelte/ArgwsPage.svelte
<script>
  import '@argws/visual-builder';
  import '@argws/visual-builder/styles.css';
  import {onMount} from 'svelte';
  export let documentUrl='/api/pages/home'; let host;
  onMount(async()=>{const r=await fetch(documentUrl);const p=await r.json();host.document=p.data?.document??p.document??p;});
</script>
<argws-page-renderer bind:this={host}></argws-page-renderer>
